### ISSUE TITLE
S2Anet 训练精度？

### ISSUE THREAD

**Issue by ccl-1** [ming71/UCAS-AOD-benchmark#7]
大佬你好，我是做遥感目标检测的小硕士一枚，我想问一下，您使用S2Anet 在ucas_aod数据集上,得到的 car精度 89（score_thresh = 0.3, iou_thresh=0.5）是如何训练的？我使用这个 算法 训练 得到car精度最高为 78 ，plane=90。使用resnet50+fpn+anchor_strides=[8, 16, 32, 64, 128]+anchor_scales=[4],batch=8, lr=0.01,linear_step=[8,11,20],total_epochs = 36.  后来loss到0.4左右就不下降了，调节学习率和epoch也没啥用，不知道怎样继续使用loss下降。  您是添加了一些其他的trick还是 简单的修改配置文件参数提升的精度？ 在线求回复。

**Comment by ming71** [comment]
你好，抱歉现在才看到，我当时好像是直接默认的config自己配上了这个数据集。你试试多训练几轮，当时我统一了训练的轮数是50还是多少来着
