### ISSUE TITLE
About the labels

### ISSUE THREAD

**Issue by fzhq** [ming71/UCAS-AOD-benchmark#9]
大佬，您好。您在使用yolov3训练时，请问是怎么处理标签的呢？

**Comment by ming71** [comment]
转化成yolo格式训练就行

**Comment by fzhq** [comment]
> 转化成yolo格式训练就行

请问您有转化的脚本吗？我试了好多次，都无法成功转化

**Comment by ming71** [comment]
参考我这个repo下面有转换代码:https://github.com/ming71/toolbox

**Comment by fzhq** [comment]
> 参考我这个repo下面有转换代码:https://github.com/ming71/toolbox

好的，谢谢大佬
